# Stage 1: Build React Application
FROM node:slim AS build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the React application
RUN npm run build

# Stage 2: Serve React Application using Nginx
FROM nginx:alpine

# Copy the built React application to the Nginx server directory
COPY --from=build /app/build /usr/share/nginx/html

# Ensure the custom 404 page is also copied
COPY ./404.html /usr/share/nginx/html/404.html

# Copy Nginx configuration
COPY ./nginx.conf /etc/nginx/templates/nginx.conf.template

# Expose port 3000 to the outside world
EXPOSE 3000

# Start Nginx server
CMD ["nginx", "-g", "daemon off;"]